Update pushapi.md
MicrosoftDocs/appcenter-docs pull request #213
Opened 2018-07-11 15:39 UTC by K232

Length limitations are shown in the Website, so added also to the docs.

2018-07-24 10:46 UTC, AmirSarmast approved these changes

2018-07-25 12:52 UTC, jwargo commented
@dimazaid please review

2018-07-25 19:09 UTC, dimazaid requested changes
Updated the file with additional info, please include them in the PR

2018-08-16 17:59 UTC, jwargo approved these changes

2018-08-16 18:00 UTC, jwargo approved these changes

2018-08-16 18:01 UTC, jwargo approved these changes

2018-08-16 18:01 UTC, merged